const ActionTypes = {
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
  REQ_GET_USERS: 'REQ_GET_USERS',

  REQ_GET_CATEGORIES: 'REQ_GET_CATEGORIES',
  GET_CATEGORIES_RESPONSE: 'GET_CATEGORIES_RESPONSE',

  ADD_USER: 'ADD_USER',
  ADD_USER_RESPONSE: 'ADD_USER_RESPONSE',
  DEL_USER: 'DEL_USER',
  DEL_USER_RESPONSE: 'DEL_USER_RESPONSE',

  REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
  GET_PRODUCTS_RESPONSE: 'GET_PRODUCTS_RESPONSE',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_RESPONSE: 'ADD_PRODUCT_RESPONSE',
  REQ_GET_PRODUCT_ID: 'REQ_GET_PRODUCT_ID',
  GET_PRODUCT_ID_RESPONSE: 'GET_PRODUCT_ID_RESPONSE',

  DEL_PRODUCT: 'DEL_PRODUCT',
  DEL_PRODUCT_RESPONSE: 'DEL_PRODUCT_RESPONSE',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_RESPONSE: 'UPDATE_PRODUCT_RESPONSE',

  ADD_CATEGORY: 'ADD_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',

  //login action
  REQ_LOGIN: 'REQ_LOGIN',
  GET_RESPONSE_LOGIN: 'GET_RESPONSE_LOGIN',

  //get paginated users
  REQ_GET_USER_PAGE: 'REQ_GET_USER_PAGE',
  GET_USER_PAGE_RESPONSE: 'GET_USER_PAGE_RESPONSE',
};

export default ActionTypes;
