const ActionTypes = {
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
  REQ_GET_USERS: 'REQ_GET_USERS',

  REQ_GET_CATEGORIES: 'REQ_GET_CATEGORIES',
  GET_CATEGORIES_RESPONSE: 'GET_CATEGORIES_RESPONSE',

  ADD_USER: 'ADD_USER',
  ADD_USER_RESPONSE: 'ADD_USER_RESPONSE',

  DEL_USER: 'DEL_USER',
  DEL_USER_RESPONSE: 'DEL_USER_RESPONSE',

  REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
  GET_PRODUCTS_RESPONSE: 'GET_PRODUCTS_RESPONSE',
  DEL_PRODUCT: 'DEL_PRODUCT',
  DEL_PRODUCT_RESPONSE: 'DEL_PRODUCT_RESPONSE',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',
};

export default ActionTypes;
